name: Playwright Tests and Deploy to S3

on:
  push:
    branches:
      - playwright-deploy  # Trigger this action only on the playwright-deploy branch

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Latest version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Install Playwright browsers
    - name: Install Playwright browsers
      run: npx playwright install

    # Step 5: Start local server
    - name: Start local server
      run: |
        npx http-server ./ -p 5500 &
        echo "Waiting for server to start..."
        timeout 30s bash -c 'until curl -s http://127.0.0.1:5500/index.html; do sleep 1; done'

    # Step 6: Run Playwright tests
    - name: Run Playwright tests
      run: npx playwright test
      env:
        BASE_URL: http://127.0.0.1:5500

  deploy:
    runs-on: ubuntu-latest
    needs: playwright-tests  # Ensure deployment runs only after Playwright tests pass

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Install AWS CLI
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    # Step 3: Deploy to S3
    - name: Deploy to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      run: |
        aws s3 sync . s3://$S3_BUCKET_NAME --delete --exclude ".git/*" --exclude ".github/*"

